Expose statsd
ansble/monument pull request #577
Opened 2018-03-27 21:28 UTC by cursiv3

Moved statsd client init and statsd import to root ```index.js``` and added ```statsd``` to export object in the same file.  The statsd client is available anywhere by ```require(monument).statsd```

However, I could not figure out a way to test, and though the client is showing I am uncertain if it will fire data to an actual statsd server.

2018-03-30 05:08 UTC, designfrontier requested changes
Awesome looking so far!

One thing that it needs is some new tests around it's exposure. The existing statsd tests (if they are passing) should cover the rest.

Just need to assert that there is a function/object returned from `require('../index').statsd`
Look for where the same kind of test exists for the event object.

2018-03-30 05:09 UTC, designfrontier commented
Looks like `  ✖ routes › router.statsd › when not configured does not send anything to statsd for each standard request ` is failing now

And also need to merge latest changes on master into your branch. 

Thanks for the work, and sorry it has taken me a few days to respond.

2018-04-07 01:29 UTC, cursiv3 commented
My trouble seems to be the config that is used to initialize the statsdClient is passed into the router, and I can't seem to find a good way to get it out of there. Is that config passed in on server start up?

2018-04-12 12:08 UTC, designfrontier commented
@cursiv3 yeah it should be passed in at server startup

2018-04-12 12:48 UTC, designfrontier commented
Ok the other random failing tests are fixed on master. If you merge master into your branch they should go away...

If I have some time over the weekend I'll pull what you have in and see if I can think of some ways to get around the issue you are running into

2026-01-17 18:02 UTC, closed without merging